name: deploy

on:
  push:
    branches:
      - 'main'
      
  pull_request:
    branches:
      - 'main'
    
  workflow_dispatch:
  
jobs:
  deploy:          
    runs-on: ubuntu-latest
    
    steps:
    - name: deploy
      uses: appleboy/ssh-action@master
      with:
        host: "192.168.194.105"
        username: "group05"
        password: "P@$$w0rd_Group05"
        port: 22
        script: |
          cd hackathon-2023-group-05
          git pull 
          docker compose --env-file .env up --build -d
          docker system prune -f
